/*
 * Created on 2018-10-02 ( Date ISO 2018-10-02 - Time 12:09:08 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package org.demo.service;



import java.util.List;

import javax.transaction.Transactional;

import org.demo.entity.Classes;
import org.demo.repository.ClassesRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

@Service
@Transactional
public class ClassesServiceImpl implements ClassesService {

	@Autowired
	private ClassesRepository classesRepository;

	@Override
	public Classes getOne(Integer classId) {
		return classesRepository.findById(classId).get();
	}

	@Override
	public Boolean delete(Integer classId) {
		if (classesRepository.getOne(classId) != null) {
			classesRepository.deleteById(classId);
			return true;
		}
		return false;
	}

	@Override
	public Classes create(Classes classes) {
		return classesRepository.save(classes);
	}

	@Override
	public Classes update(Classes classesToUpdate) {
						Classes classes = classesRepository.getOne(classesToUpdate.getClassId());
														
				if(classesToUpdate.getClassName() !=null) {
			
		}
				if(classesToUpdate.getClassDescription() !=null) {
			
		}
				return classesRepository.save(classes);
	}

	@Override
	public Boolean exist(Classes classes) {
						return classesRepository.existsById(classes.getClassId());
													}

	@Override
	public List<Classes> findAll() {
		return classesRepository.findAll();
	}

}


