/*
 * Created on 2018-10-02 ( Date ISO 2018-10-02 - Time 12:02:34 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package org.demo.service;

import org.demo.entity.Classes;
import java.util.List;

public interface ClassesService {

	public Classes getOne(Integer classId);

	public List<Classes> findAll();

	public Boolean delete(Integer classId);

	public Classes create(Classes classes);

	public Classes update(Classes classes);

	public Boolean exist(Classes classes);
}
