/*
 * Created on 2018-10-02 ( Date ISO 2018-10-02 - Time 12:02:34 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package org.demo.service;

import org.demo.entity.ParentsAndGuardians;
import java.util.List;

public interface ParentsAndGuardiansService {

	public ParentsAndGuardians getOne(Integer personId);

	public List<ParentsAndGuardians> findAll();

	public Boolean delete(Integer personId);

	public ParentsAndGuardians create(ParentsAndGuardians parentsAndGuardians);

	public ParentsAndGuardians update(ParentsAndGuardians parentsAndGuardians);

	public Boolean exist(ParentsAndGuardians parentsAndGuardians);
}
