/*
 * Created on 2018-10-02 ( Date ISO 2018-10-02 - Time 12:02:34 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package org.demo.service;

import org.demo.entity.PropertyOwners;
import java.util.List;

public interface PropertyOwnersService {

	public PropertyOwners getOne(Integer landlordId);

	public List<PropertyOwners> findAll();

	public Boolean delete(Integer landlordId);

	public PropertyOwners create(PropertyOwners propertyOwners);

	public PropertyOwners update(PropertyOwners propertyOwners);

	public Boolean exist(PropertyOwners propertyOwners);
}
