/*
 * Created on 2018-10-02 ( Date ISO 2018-10-02 - Time 12:02:34 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package org.demo.service;

import org.demo.entity.RefAddressTypes;
import java.util.List;

public interface RefAddressTypesService {

	public RefAddressTypes getOne(Integer addressTypeCode);

	public List<RefAddressTypes> findAll();

	public Boolean delete(Integer addressTypeCode);

	public RefAddressTypes create(RefAddressTypes refAddressTypes);

	public RefAddressTypes update(RefAddressTypes refAddressTypes);

	public Boolean exist(RefAddressTypes refAddressTypes);
}
