/*
 * Created on 2018-10-02 ( Date ISO 2018-10-02 - Time 12:09:08 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package org.demo.service;



import java.util.List;

import javax.transaction.Transactional;

import org.demo.entity.RefPaymentMethods;
import org.demo.repository.RefPaymentMethodsRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

@Service
@Transactional
public class RefPaymentMethodsServiceImpl implements RefPaymentMethodsService {

	@Autowired
	private RefPaymentMethodsRepository refPaymentMethodsRepository;

	@Override
	public RefPaymentMethods getOne(Integer paymentMethodCode) {
		return refPaymentMethodsRepository.findById(paymentMethodCode).get();
	}

	@Override
	public Boolean delete(Integer paymentMethodCode) {
		if (refPaymentMethodsRepository.getOne(paymentMethodCode) != null) {
			refPaymentMethodsRepository.deleteById(paymentMethodCode);
			return true;
		}
		return false;
	}

	@Override
	public RefPaymentMethods create(RefPaymentMethods refPaymentMethods) {
		return refPaymentMethodsRepository.save(refPaymentMethods);
	}

	@Override
	public RefPaymentMethods update(RefPaymentMethods refPaymentMethodsToUpdate) {
						RefPaymentMethods refPaymentMethods = refPaymentMethodsRepository.getOne(refPaymentMethodsToUpdate.getPaymentMethodCode());
										
				if(refPaymentMethodsToUpdate.getPaymentMethodDescription() !=null) {
			
		}
				return refPaymentMethodsRepository.save(refPaymentMethods);
	}

	@Override
	public Boolean exist(RefPaymentMethods refPaymentMethods) {
						return refPaymentMethodsRepository.existsById(refPaymentMethods.getPaymentMethodCode());
									}

	@Override
	public List<RefPaymentMethods> findAll() {
		return refPaymentMethodsRepository.findAll();
	}

}


