/*
 * Created on 2018-10-02 ( Date ISO 2018-10-02 - Time 12:02:34 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package org.demo.service;

import org.demo.entity.RefPaymentMethods;
import java.util.List;

public interface RefPaymentMethodsService {

	public RefPaymentMethods getOne(Integer paymentMethodCode);

	public List<RefPaymentMethods> findAll();

	public Boolean delete(Integer paymentMethodCode);

	public RefPaymentMethods create(RefPaymentMethods refPaymentMethods);

	public RefPaymentMethods update(RefPaymentMethods refPaymentMethods);

	public Boolean exist(RefPaymentMethods refPaymentMethods);
}
