/*
 * Created on 2018-10-02 ( Date ISO 2018-10-02 - Time 12:02:34 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package org.demo.service;

import org.demo.entity.RefRelationshipTypes;
import java.util.List;

public interface RefRelationshipTypesService {

	public RefRelationshipTypes getOne(Integer relationshipTypeCode);

	public List<RefRelationshipTypes> findAll();

	public Boolean delete(Integer relationshipTypeCode);

	public RefRelationshipTypes create(RefRelationshipTypes refRelationshipTypes);

	public RefRelationshipTypes update(RefRelationshipTypes refRelationshipTypes);

	public Boolean exist(RefRelationshipTypes refRelationshipTypes);
}
