/*
 * Created on 2018-10-02 ( Date ISO 2018-10-02 - Time 12:09:08 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package org.demo.service;



import java.util.List;

import javax.transaction.Transactional;

import org.demo.entity.RefRelationshipTypes;
import org.demo.repository.RefRelationshipTypesRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

@Service
@Transactional
public class RefRelationshipTypesServiceImpl implements RefRelationshipTypesService {

	@Autowired
	private RefRelationshipTypesRepository refRelationshipTypesRepository;

	@Override
	public RefRelationshipTypes getOne(Integer relationshipTypeCode) {
		return refRelationshipTypesRepository.findById(relationshipTypeCode).get();
	}

	@Override
	public Boolean delete(Integer relationshipTypeCode) {
		if (refRelationshipTypesRepository.getOne(relationshipTypeCode) != null) {
			refRelationshipTypesRepository.deleteById(relationshipTypeCode);
			return true;
		}
		return false;
	}

	@Override
	public RefRelationshipTypes create(RefRelationshipTypes refRelationshipTypes) {
		return refRelationshipTypesRepository.save(refRelationshipTypes);
	}

	@Override
	public RefRelationshipTypes update(RefRelationshipTypes refRelationshipTypesToUpdate) {
						RefRelationshipTypes refRelationshipTypes = refRelationshipTypesRepository.getOne(refRelationshipTypesToUpdate.getRelationshipTypeCode());
										
				if(refRelationshipTypesToUpdate.getRelationshipTypeDescription() !=null) {
			
		}
				return refRelationshipTypesRepository.save(refRelationshipTypes);
	}

	@Override
	public Boolean exist(RefRelationshipTypes refRelationshipTypes) {
						return refRelationshipTypesRepository.existsById(refRelationshipTypes.getRelationshipTypeCode());
									}

	@Override
	public List<RefRelationshipTypes> findAll() {
		return refRelationshipTypesRepository.findAll();
	}

}


