/*
 * Created on 2018-10-02 ( Date ISO 2018-10-02 - Time 12:09:08 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package org.demo.service;



import java.util.List;

import javax.transaction.Transactional;

import org.demo.entity.Students;
import org.demo.repository.StudentsRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

@Service
@Transactional
public class StudentsServiceImpl implements StudentsService {

	@Autowired
	private StudentsRepository studentsRepository;

	@Override
	public Students getOne(Integer studentId) {
		return studentsRepository.findById(studentId).get();
	}

	@Override
	public Boolean delete(Integer studentId) {
		if (studentsRepository.getOne(studentId) != null) {
			studentsRepository.deleteById(studentId);
			return true;
		}
		return false;
	}

	@Override
	public Students create(Students students) {
		return studentsRepository.save(students);
	}

	@Override
	public Students update(Students studentsToUpdate) {
						Students students = studentsRepository.getOne(studentsToUpdate.getStudentId());
																																										
				if(studentsToUpdate.getGender() !=null) {
			
		}
				if(studentsToUpdate.getFirstName() !=null) {
			
		}
				if(studentsToUpdate.getMiddleName() !=null) {
			
		}
				if(studentsToUpdate.getLastName() !=null) {
			
		}
				if(studentsToUpdate.getCellMobileNumber() !=null) {
			
		}
				if(studentsToUpdate.getEmailAddress() !=null) {
			
		}
				if(studentsToUpdate.getDateFirstRental() !=null) {
			
		}
				if(studentsToUpdate.getDateLeftUniversity() !=null) {
			
		}
				if(studentsToUpdate.getOtherStudentDetails() !=null) {
			
		}
				return studentsRepository.save(students);
	}

	@Override
	public Boolean exist(Students students) {
						return studentsRepository.existsById(students.getStudentId());
																																									}

	@Override
	public List<Students> findAll() {
		return studentsRepository.findAll();
	}

}


