/*
 * Created on 2018-10-02 ( Date ISO 2018-10-02 - Time 12:02:34 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package org.demo.service;

import org.demo.entity.StudentAddress;
import java.util.List;

public interface StudentAddressService {

	public StudentAddress getOne(Integer studentAddressId);

	public List<StudentAddress> findAll();

	public Boolean delete(Integer studentAddressId);

	public StudentAddress create(StudentAddress studentAddress);

	public StudentAddress update(StudentAddress studentAddress);

	public Boolean exist(StudentAddress studentAddress);
}
