/*
 * Created on 2018-10-02 ( Date ISO 2018-10-02 - Time 12:09:08 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package org.demo.service;



import java.util.List;

import javax.transaction.Transactional;

import org.demo.entity.StudentAddress;
import org.demo.repository.StudentAddressRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

@Service
@Transactional
public class StudentAddressServiceImpl implements StudentAddressService {

	@Autowired
	private StudentAddressRepository studentAddressRepository;

	@Override
	public StudentAddress getOne(Integer studentAddressId) {
		return studentAddressRepository.findById(studentAddressId).get();
	}

	@Override
	public Boolean delete(Integer studentAddressId) {
		if (studentAddressRepository.getOne(studentAddressId) != null) {
			studentAddressRepository.deleteById(studentAddressId);
			return true;
		}
		return false;
	}

	@Override
	public StudentAddress create(StudentAddress studentAddress) {
		return studentAddressRepository.save(studentAddress);
	}

	@Override
	public StudentAddress update(StudentAddress studentAddressToUpdate) {
						StudentAddress studentAddress = studentAddressRepository.getOne(studentAddressToUpdate.getStudentAddressId());
																																		

				if(studentAddressToUpdate.getDateAddressFrom() !=null) {
			
		}
				if(studentAddressToUpdate.getDateAddressTo() !=null) {
			
		}
				if(studentAddressToUpdate.getMonthlyRental() !=null) {
			
		}
				if(studentAddressToUpdate.getOtherDetails() !=null) {
			
		}
				return studentAddressRepository.save(studentAddress);
	}

	@Override
	public Boolean exist(StudentAddress studentAddress) {
						return studentAddressRepository.existsById(studentAddress.getStudentAddressId());
																																	}

	@Override
	public List<StudentAddress> findAll() {
		return studentAddressRepository.findAll();
	}

}


