/*
 * Created on 2018-10-02 ( Date ISO 2018-10-02 - Time 12:02:34 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package org.demo.service;

import org.demo.entity.StudentsPaymentMethods;
import java.util.List;

public interface StudentsPaymentMethodsService {

	public StudentsPaymentMethods getOne(Integer studentPaymentMethodId);

	public List<StudentsPaymentMethods> findAll();

	public Boolean delete(Integer studentPaymentMethodId);

	public StudentsPaymentMethods create(StudentsPaymentMethods studentsPaymentMethods);

	public StudentsPaymentMethods update(StudentsPaymentMethods studentsPaymentMethods);

	public Boolean exist(StudentsPaymentMethods studentsPaymentMethods);
}
