/*
 * Created on 2018-10-02 ( Date ISO 2018-10-02 - Time 12:02:34 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package org.demo.service;

import org.demo.entity.StudentRelationships;
import org.demo.entity.StudentRelationshipsId;
import java.util.List;

public interface StudentRelationshipsService {

	public StudentRelationships getOne(StudentRelationshipsId studentRelationshipsId);

	public List<StudentRelationships> findAll();

	public Boolean delete(StudentRelationshipsId studentRelationshipsId);

	public StudentRelationships create(StudentRelationships studentRelationships);

	public StudentRelationships update(StudentRelationships studentRelationshipsToUpdate );

	public Boolean exist(StudentRelationshipsId studentRelationshipsId);
}
