/*
 * Created on 2018-10-02 ( Date ISO 2018-10-02 - Time 12:02:34 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package org.demo.service;

import org.demo.entity.Students;
import java.util.List;

public interface StudentsService {

	public Students getOne(Integer studentId);

	public List<Students> findAll();

	public Boolean delete(Integer studentId);

	public Students create(Students students);

	public Students update(Students students);

	public Boolean exist(Students students);
}
