/*
 * Created on 2018-10-02 ( Date ISO 2018-10-02 - Time 12:09:08 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package org.demo.service.criteria;

/**
 * Criteria bean used for Addresses search.
 * @author Telosys (http://www.telosys.org/) version 3.0.0
 */
public class AddressesCriteria {

    private String universityAccomodationYn; 
    private String line1NumberBuilding; 
    private String line2NumberStreet; 
    private String line3AreaLocality; 
    private String city; 
    private String zipPostcode; 
    private String stateProvinceCounty; 
    private String country; 
    private String otherAddressDetails; 
	// Constructor
	public AddressesCriteria() {
		// Needed empty constructor for serialization
	}

	public void setUniversityAccomodationYn(String universityAccomodationYn) {this.universityAccomodationYn = universityAccomodationYn;}
	public String getUniversityAccomodationYn() {return this.universityAccomodationYn;}
	public void setLine1NumberBuilding(String line1NumberBuilding) {this.line1NumberBuilding = line1NumberBuilding;}
	public String getLine1NumberBuilding() {return this.line1NumberBuilding;}
	public void setLine2NumberStreet(String line2NumberStreet) {this.line2NumberStreet = line2NumberStreet;}
	public String getLine2NumberStreet() {return this.line2NumberStreet;}
	public void setLine3AreaLocality(String line3AreaLocality) {this.line3AreaLocality = line3AreaLocality;}
	public String getLine3AreaLocality() {return this.line3AreaLocality;}
	public void setCity(String city) {this.city = city;}
	public String getCity() {return this.city;}
	public void setZipPostcode(String zipPostcode) {this.zipPostcode = zipPostcode;}
	public String getZipPostcode() {return this.zipPostcode;}
	public void setStateProvinceCounty(String stateProvinceCounty) {this.stateProvinceCounty = stateProvinceCounty;}
	public String getStateProvinceCounty() {return this.stateProvinceCounty;}
	public void setCountry(String country) {this.country = country;}
	public String getCountry() {return this.country;}
	public void setOtherAddressDetails(String otherAddressDetails) {this.otherAddressDetails = otherAddressDetails;}
	public String getOtherAddressDetails() {return this.otherAddressDetails;}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder(); 
		sb.append(universityAccomodationYn); 
		sb.append("|"); 
		sb.append(line1NumberBuilding); 
		sb.append("|"); 
		sb.append(line2NumberStreet); 
		sb.append("|"); 
		sb.append(line3AreaLocality); 
		sb.append("|"); 
		sb.append(city); 
		sb.append("|"); 
		sb.append(zipPostcode); 
		sb.append("|"); 
		sb.append(stateProvinceCounty); 
		sb.append("|"); 
		sb.append(country); 
		sb.append("|"); 
		sb.append(otherAddressDetails); 
        return sb.toString();
	}
}
