/*
 * Created on 2018-10-02 ( Date ISO 2018-10-02 - Time 12:09:08 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package org.demo.service.criteria;

/**
 * Criteria bean used for PropertyOwners search.
 * @author Telosys (http://www.telosys.org/) version 3.0.0
 */
public class PropertyOwnersCriteria {

    private String landlordName; 
    private String dateFirstRental; 
    private String otherLandlordDetails; 
	// Constructor
	public PropertyOwnersCriteria() {
		// Needed empty constructor for serialization
	}

	public void setLandlordName(String landlordName) {this.landlordName = landlordName;}
	public String getLandlordName() {return this.landlordName;}
	public void setDateFirstRental(String dateFirstRental) {this.dateFirstRental = dateFirstRental;}
	public String getDateFirstRental() {return this.dateFirstRental;}
	public void setOtherLandlordDetails(String otherLandlordDetails) {this.otherLandlordDetails = otherLandlordDetails;}
	public String getOtherLandlordDetails() {return this.otherLandlordDetails;}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder(); 
		sb.append(landlordName); 
		sb.append("|"); 
		sb.append(dateFirstRental); 
		sb.append("|"); 
		sb.append(otherLandlordDetails); 
        return sb.toString();
	}
}
