/*
 * Created on 2018-10-02 ( Date ISO 2018-10-02 - Time 12:09:08 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package org.demo.service.criteria;

/**
 * Criteria bean used for RefPaymentMethods search.
 * @author Telosys (http://www.telosys.org/) version 3.0.0
 */
public class RefPaymentMethodsCriteria {

    private String paymentMethodDescription; 
	// Constructor
	public RefPaymentMethodsCriteria() {
		// Needed empty constructor for serialization
	}

	public void setPaymentMethodDescription(String paymentMethodDescription) {this.paymentMethodDescription = paymentMethodDescription;}
	public String getPaymentMethodDescription() {return this.paymentMethodDescription;}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder(); 
		sb.append(paymentMethodDescription); 
        return sb.toString();
	}
}
