/*
 * Created on 2018-10-02 ( Date ISO 2018-10-02 - Time 12:09:08 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package org.demo.service.criteria;

/**
 * Criteria bean used for RefRelationshipTypes search.
 * @author Telosys (http://www.telosys.org/) version 3.0.0
 */
public class RefRelationshipTypesCriteria {

    private String relationshipTypeDescription; 
	// Constructor
	public RefRelationshipTypesCriteria() {
		// Needed empty constructor for serialization
	}

	public void setRelationshipTypeDescription(String relationshipTypeDescription) {this.relationshipTypeDescription = relationshipTypeDescription;}
	public String getRelationshipTypeDescription() {return this.relationshipTypeDescription;}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder(); 
		sb.append(relationshipTypeDescription); 
        return sb.toString();
	}
}
