/*
 * Created on 2018-10-02 ( Date ISO 2018-10-02 - Time 12:09:08 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package org.demo.service.criteria;

/**
 * Criteria bean used for StudentClassRegistrations search.
 * @author Telosys (http://www.telosys.org/) version 3.0.0
 */
public class StudentClassRegistrationsCriteria {

    private String otherDetails; 
	// Constructor
	public StudentClassRegistrationsCriteria() {
		// Needed empty constructor for serialization
	}

	public void setOtherDetails(String otherDetails) {this.otherDetails = otherDetails;}
	public String getOtherDetails() {return this.otherDetails;}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder(); 
		sb.append(otherDetails); 
        return sb.toString();
	}
}
