package org.demo.entity;
// Generated Oct 2, 2018 12:02:13 PM by Hibernate Tools 5.2.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Addresses generated by hbm2java
 */
@Entity
@Table(name = "addresses", catalog = "studentregistration")
public class Addresses implements java.io.Serializable {

	private Integer addressId;
	private PropertyOwners propertyOwners;
	private String universityAccomodationYn;
	private String line1NumberBuilding;
	private String line2NumberStreet;
	private String line3AreaLocality;
	private String city;
	private String zipPostcode;
	private String stateProvinceCounty;
	private String country;
	private String otherAddressDetails;
	private Set<ParentsAndGuardians> parentsAndGuardianses = new HashSet<ParentsAndGuardians>(0);
	private Set<StudentAddress> studentAddresses = new HashSet<StudentAddress>(0);

	public Addresses() {
	}

	public Addresses(PropertyOwners propertyOwners, String universityAccomodationYn, String line1NumberBuilding,
			String line2NumberStreet, String line3AreaLocality, String city, String zipPostcode,
			String stateProvinceCounty, String country, String otherAddressDetails,
			Set<ParentsAndGuardians> parentsAndGuardianses, Set<StudentAddress> studentAddresses) {
		this.propertyOwners = propertyOwners;
		this.universityAccomodationYn = universityAccomodationYn;
		this.line1NumberBuilding = line1NumberBuilding;
		this.line2NumberStreet = line2NumberStreet;
		this.line3AreaLocality = line3AreaLocality;
		this.city = city;
		this.zipPostcode = zipPostcode;
		this.stateProvinceCounty = stateProvinceCounty;
		this.country = country;
		this.otherAddressDetails = otherAddressDetails;
		this.parentsAndGuardianses = parentsAndGuardianses;
		this.studentAddresses = studentAddresses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "address_id", unique = true, nullable = false)
	public Integer getAddressId() {
		return this.addressId;
	}

	public void setAddressId(Integer addressId) {
		this.addressId = addressId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "landlord_id")
	public PropertyOwners getPropertyOwners() {
		return this.propertyOwners;
	}

	public void setPropertyOwners(PropertyOwners propertyOwners) {
		this.propertyOwners = propertyOwners;
	}

	@Column(name = "university_accomodation_yn", length = 45)
	public String getUniversityAccomodationYn() {
		return this.universityAccomodationYn;
	}

	public void setUniversityAccomodationYn(String universityAccomodationYn) {
		this.universityAccomodationYn = universityAccomodationYn;
	}

	@Column(name = "line_1_number_building", length = 45)
	public String getLine1NumberBuilding() {
		return this.line1NumberBuilding;
	}

	public void setLine1NumberBuilding(String line1NumberBuilding) {
		this.line1NumberBuilding = line1NumberBuilding;
	}

	@Column(name = "line_2_number_street", length = 45)
	public String getLine2NumberStreet() {
		return this.line2NumberStreet;
	}

	public void setLine2NumberStreet(String line2NumberStreet) {
		this.line2NumberStreet = line2NumberStreet;
	}

	@Column(name = "line_3_area_locality", length = 45)
	public String getLine3AreaLocality() {
		return this.line3AreaLocality;
	}

	public void setLine3AreaLocality(String line3AreaLocality) {
		this.line3AreaLocality = line3AreaLocality;
	}

	@Column(name = "city", length = 45)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "zip_postcode", length = 45)
	public String getZipPostcode() {
		return this.zipPostcode;
	}

	public void setZipPostcode(String zipPostcode) {
		this.zipPostcode = zipPostcode;
	}

	@Column(name = "state_province_county", length = 45)
	public String getStateProvinceCounty() {
		return this.stateProvinceCounty;
	}

	public void setStateProvinceCounty(String stateProvinceCounty) {
		this.stateProvinceCounty = stateProvinceCounty;
	}

	@Column(name = "country", length = 45)
	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	@Column(name = "other_address_details", length = 45)
	public String getOtherAddressDetails() {
		return this.otherAddressDetails;
	}

	public void setOtherAddressDetails(String otherAddressDetails) {
		this.otherAddressDetails = otherAddressDetails;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "addresses")
	public Set<ParentsAndGuardians> getParentsAndGuardianses() {
		return this.parentsAndGuardianses;
	}

	public void setParentsAndGuardianses(Set<ParentsAndGuardians> parentsAndGuardianses) {
		this.parentsAndGuardianses = parentsAndGuardianses;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "addresses")
	public Set<StudentAddress> getStudentAddresses() {
		return this.studentAddresses;
	}

	public void setStudentAddresses(Set<StudentAddress> studentAddresses) {
		this.studentAddresses = studentAddresses;
	}

	@Override
	public String toString() {
		return "Addresses [addressId=" + addressId + ", propertyOwners=" + propertyOwners
				+ ", universityAccomodationYn=" + universityAccomodationYn + ", line1NumberBuilding="
				+ line1NumberBuilding + ", line2NumberStreet=" + line2NumberStreet + ", line3AreaLocality="
				+ line3AreaLocality + ", city=" + city + ", zipPostcode=" + zipPostcode + ", stateProvinceCounty="
				+ stateProvinceCounty + ", country=" + country + ", otherAddressDetails=" + otherAddressDetails
				+ ", parentsAndGuardianses=" + parentsAndGuardianses + ", studentAddresses=" + studentAddresses + "]";
	}
	

}
