package org.demo.entity;
// Generated Oct 2, 2018 12:02:13 PM by Hibernate Tools 5.2.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Classes generated by hbm2java
 */
@Entity
@Table(name = "classes", catalog = "studentregistration")
public class Classes implements java.io.Serializable {

	private Integer classId;
	private String className;
	private String classDescription;
	private Set<StudentClassRegistrations> studentClassRegistrationses = new HashSet<StudentClassRegistrations>(0);

	public Classes() {
	}

	public Classes(String className, String classDescription,
			Set<StudentClassRegistrations> studentClassRegistrationses) {
		this.className = className;
		this.classDescription = classDescription;
		this.studentClassRegistrationses = studentClassRegistrationses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "class_id", unique = true, nullable = false)
	public Integer getClassId() {
		return this.classId;
	}

	public void setClassId(Integer classId) {
		this.classId = classId;
	}

	@Column(name = "class_name", length = 45)
	public String getClassName() {
		return this.className;
	}

	public void setClassName(String className) {
		this.className = className;
	}

	@Column(name = "class_description", length = 45)
	public String getClassDescription() {
		return this.classDescription;
	}

	public void setClassDescription(String classDescription) {
		this.classDescription = classDescription;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "classes")
	public Set<StudentClassRegistrations> getStudentClassRegistrationses() {
		return this.studentClassRegistrationses;
	}

	public void setStudentClassRegistrationses(Set<StudentClassRegistrations> studentClassRegistrationses) {
		this.studentClassRegistrationses = studentClassRegistrationses;
	}

}
