package org.demo.entity;
// Generated Oct 2, 2018 12:02:13 PM by Hibernate Tools 5.2.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ParentsAndGuardians generated by hbm2java
 */
@Entity
@Table(name = "parents_and_guardians", catalog = "studentregistration")
public class ParentsAndGuardians implements java.io.Serializable {

	private Integer personId;
	private Addresses addresses;
	private String gender;
	private String firstName;
	private String middleName;
	private String lastName;
	private String cellMobileNumber;
	private String emailAddress;
	private String otherDetails;
	private Set<StudentRelationships> studentRelationshipses = new HashSet<StudentRelationships>(0);

	public ParentsAndGuardians() {
	}

	public ParentsAndGuardians(Addresses addresses, String gender, String firstName, String middleName, String lastName,
			String cellMobileNumber, String emailAddress, String otherDetails,
			Set<StudentRelationships> studentRelationshipses) {
		this.addresses = addresses;
		this.gender = gender;
		this.firstName = firstName;
		this.middleName = middleName;
		this.lastName = lastName;
		this.cellMobileNumber = cellMobileNumber;
		this.emailAddress = emailAddress;
		this.otherDetails = otherDetails;
		this.studentRelationshipses = studentRelationshipses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "person_id", unique = true, nullable = false)
	public Integer getPersonId() {
		return this.personId;
	}

	public void setPersonId(Integer personId) {
		this.personId = personId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "address_id")
	public Addresses getAddresses() {
		return this.addresses;
	}

	public void setAddresses(Addresses addresses) {
		this.addresses = addresses;
	}

	@Column(name = "gender", length = 45)
	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	@Column(name = "first_name", length = 45)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "middle_name", length = 45)
	public String getMiddleName() {
		return this.middleName;
	}

	public void setMiddleName(String middleName) {
		this.middleName = middleName;
	}

	@Column(name = "last_name", length = 45)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Column(name = "cell_mobile_number", length = 45)
	public String getCellMobileNumber() {
		return this.cellMobileNumber;
	}

	public void setCellMobileNumber(String cellMobileNumber) {
		this.cellMobileNumber = cellMobileNumber;
	}

	@Column(name = "email_address", length = 45)
	public String getEmailAddress() {
		return this.emailAddress;
	}

	public void setEmailAddress(String emailAddress) {
		this.emailAddress = emailAddress;
	}

	@Column(name = "other_details", length = 45)
	public String getOtherDetails() {
		return this.otherDetails;
	}

	public void setOtherDetails(String otherDetails) {
		this.otherDetails = otherDetails;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "parentsAndGuardians")
	public Set<StudentRelationships> getStudentRelationshipses() {
		return this.studentRelationshipses;
	}

	public void setStudentRelationshipses(Set<StudentRelationships> studentRelationshipses) {
		this.studentRelationshipses = studentRelationshipses;
	}

}
