package org.demo.entity;
// Generated Oct 2, 2018 12:02:13 PM by Hibernate Tools 5.2.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PropertyOwners generated by hbm2java
 */
@Entity
@Table(name = "property_owners", catalog = "studentregistration")
public class PropertyOwners implements java.io.Serializable {

	private Integer landlordId;
	private String landlordName;
	private String dateFirstRental;
	private String otherLandlordDetails;
	private Set<Addresses> addresseses = new HashSet<Addresses>(0);

	public PropertyOwners() {
	}

	public PropertyOwners(String landlordName, String dateFirstRental, String otherLandlordDetails,
			Set<Addresses> addresseses) {
		this.landlordName = landlordName;
		this.dateFirstRental = dateFirstRental;
		this.otherLandlordDetails = otherLandlordDetails;
		this.addresseses = addresseses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "landlord_id", unique = true, nullable = false)
	public Integer getLandlordId() {
		return this.landlordId;
	}

	public void setLandlordId(Integer landlordId) {
		this.landlordId = landlordId;
	}

	@Column(name = "landlord_name", length = 45)
	public String getLandlordName() {
		return this.landlordName;
	}

	public void setLandlordName(String landlordName) {
		this.landlordName = landlordName;
	}

	@Column(name = "date_first_rental", length = 45)
	public String getDateFirstRental() {
		return this.dateFirstRental;
	}

	public void setDateFirstRental(String dateFirstRental) {
		this.dateFirstRental = dateFirstRental;
	}

	@Column(name = "other_landlord_details", length = 45)
	public String getOtherLandlordDetails() {
		return this.otherLandlordDetails;
	}

	public void setOtherLandlordDetails(String otherLandlordDetails) {
		this.otherLandlordDetails = otherLandlordDetails;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "propertyOwners")
	public Set<Addresses> getAddresseses() {
		return this.addresseses;
	}

	public void setAddresseses(Set<Addresses> addresseses) {
		this.addresseses = addresseses;
	}

//	@Override
//	public String toString() {
//		return "PropertyOwners [landlordId=" + landlordId + ", landlordName=" + landlordName + ", dateFirstRental="
//				+ dateFirstRental + ", otherLandlordDetails=" + otherLandlordDetails + ", addresseses=" + addresseses
//				+ "]";
//	}
	

}
