package org.demo.entity;
// Generated Oct 2, 2018 12:02:13 PM by Hibernate Tools 5.2.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * RefAddressTypes generated by hbm2java
 */
@Entity
@Table(name = "ref_address_types", catalog = "studentregistration")
public class RefAddressTypes implements java.io.Serializable {

	private Integer addressTypeCode;
	private String addressTypeDescription;
	private Set<StudentAddress> studentAddresses = new HashSet<StudentAddress>(0);

	public RefAddressTypes() {
	}

	public RefAddressTypes(String addressTypeDescription, Set<StudentAddress> studentAddresses) {
		this.addressTypeDescription = addressTypeDescription;
		this.studentAddresses = studentAddresses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "address_type_code", unique = true, nullable = false)
	public Integer getAddressTypeCode() {
		return this.addressTypeCode;
	}

	public void setAddressTypeCode(Integer addressTypeCode) {
		this.addressTypeCode = addressTypeCode;
	}

	@Column(name = "address_type_description", length = 45)
	public String getAddressTypeDescription() {
		return this.addressTypeDescription;
	}

	public void setAddressTypeDescription(String addressTypeDescription) {
		this.addressTypeDescription = addressTypeDescription;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "refAddressTypes")
	public Set<StudentAddress> getStudentAddresses() {
		return this.studentAddresses;
	}

	public void setStudentAddresses(Set<StudentAddress> studentAddresses) {
		this.studentAddresses = studentAddresses;
	}

}
