package org.demo.entity;
// Generated Oct 2, 2018 12:02:13 PM by Hibernate Tools 5.2.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * RefPaymentMethods generated by hbm2java
 */
@Entity
@Table(name = "ref_payment_methods", catalog = "studentregistration")
public class RefPaymentMethods implements java.io.Serializable {

	private Integer paymentMethodCode;
	private String paymentMethodDescription;
	private Set<StudentsPaymentMethods> studentsPaymentMethodses = new HashSet<StudentsPaymentMethods>(0);

	public RefPaymentMethods() {
	}

	public RefPaymentMethods(String paymentMethodDescription, Set<StudentsPaymentMethods> studentsPaymentMethodses) {
		this.paymentMethodDescription = paymentMethodDescription;
		this.studentsPaymentMethodses = studentsPaymentMethodses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "payment_method_code", unique = true, nullable = false)
	public Integer getPaymentMethodCode() {
		return this.paymentMethodCode;
	}

	public void setPaymentMethodCode(Integer paymentMethodCode) {
		this.paymentMethodCode = paymentMethodCode;
	}

	@Column(name = "payment_method_description", length = 45)
	public String getPaymentMethodDescription() {
		return this.paymentMethodDescription;
	}

	public void setPaymentMethodDescription(String paymentMethodDescription) {
		this.paymentMethodDescription = paymentMethodDescription;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "refPaymentMethods")
	public Set<StudentsPaymentMethods> getStudentsPaymentMethodses() {
		return this.studentsPaymentMethodses;
	}

	public void setStudentsPaymentMethodses(Set<StudentsPaymentMethods> studentsPaymentMethodses) {
		this.studentsPaymentMethodses = studentsPaymentMethodses;
	}

}
