package org.demo.entity;
// Generated Oct 2, 2018 12:02:13 PM by Hibernate Tools 5.2.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * RefRelationshipTypes generated by hbm2java
 */
@Entity
@Table(name = "ref_relationship_types", catalog = "studentregistration")
public class RefRelationshipTypes implements java.io.Serializable {

	private Integer relationshipTypeCode;
	private String relationshipTypeDescription;
	private Set<StudentRelationships> studentRelationshipses = new HashSet<StudentRelationships>(0);

	public RefRelationshipTypes() {
	}

	public RefRelationshipTypes(String relationshipTypeDescription, Set<StudentRelationships> studentRelationshipses) {
		this.relationshipTypeDescription = relationshipTypeDescription;
		this.studentRelationshipses = studentRelationshipses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "relationship_type_code", unique = true, nullable = false)
	public Integer getRelationshipTypeCode() {
		return this.relationshipTypeCode;
	}

	public void setRelationshipTypeCode(Integer relationshipTypeCode) {
		this.relationshipTypeCode = relationshipTypeCode;
	}

	@Column(name = "relationship_type_description", length = 45)
	public String getRelationshipTypeDescription() {
		return this.relationshipTypeDescription;
	}

	public void setRelationshipTypeDescription(String relationshipTypeDescription) {
		this.relationshipTypeDescription = relationshipTypeDescription;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "refRelationshipTypes")
	public Set<StudentRelationships> getStudentRelationshipses() {
		return this.studentRelationshipses;
	}

	public void setStudentRelationshipses(Set<StudentRelationships> studentRelationshipses) {
		this.studentRelationshipses = studentRelationshipses;
	}

}
