package org.demo.entity;
// Generated Oct 2, 2018 12:02:13 PM by Hibernate Tools 5.2.10.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Students generated by hbm2java
 */
@Entity
@Table(name = "students", catalog = "studentregistration")
public class Students implements java.io.Serializable {

	private Integer studentId;
	private String gender;
	private String firstName;
	private String middleName;
	private String lastName;
	private String cellMobileNumber;
	private String emailAddress;
	private Date dateFirstRental;
	private Date dateLeftUniversity;
	private String otherStudentDetails;
	private Set<StudentRelationships> studentRelationshipses = new HashSet<StudentRelationships>(0);
	private Set<StudentClassRegistrations> studentClassRegistrationses = new HashSet<StudentClassRegistrations>(0);
	private Set<StudentsPaymentMethods> studentsPaymentMethodses = new HashSet<StudentsPaymentMethods>(0);
	private Set<StudentAddress> studentAddresses = new HashSet<StudentAddress>(0);

	public Students() {
	}

	public Students(String gender, String firstName, String middleName, String lastName, String cellMobileNumber,
			String emailAddress, Date dateFirstRental, Date dateLeftUniversity, String otherStudentDetails,
			Set<StudentRelationships> studentRelationshipses,
			Set<StudentClassRegistrations> studentClassRegistrationses,
			Set<StudentsPaymentMethods> studentsPaymentMethodses, Set<StudentAddress> studentAddresses) {
		this.gender = gender;
		this.firstName = firstName;
		this.middleName = middleName;
		this.lastName = lastName;
		this.cellMobileNumber = cellMobileNumber;
		this.emailAddress = emailAddress;
		this.dateFirstRental = dateFirstRental;
		this.dateLeftUniversity = dateLeftUniversity;
		this.otherStudentDetails = otherStudentDetails;
		this.studentRelationshipses = studentRelationshipses;
		this.studentClassRegistrationses = studentClassRegistrationses;
		this.studentsPaymentMethodses = studentsPaymentMethodses;
		this.studentAddresses = studentAddresses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "student_id", unique = true, nullable = false)
	public Integer getStudentId() {
		return this.studentId;
	}

	public void setStudentId(Integer studentId) {
		this.studentId = studentId;
	}

	@Column(name = "gender", length = 45)
	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	@Column(name = "first_name", length = 45)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "middle_name", length = 45)
	public String getMiddleName() {
		return this.middleName;
	}

	public void setMiddleName(String middleName) {
		this.middleName = middleName;
	}

	@Column(name = "last_name", length = 45)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Column(name = "cell_mobile_number", length = 45)
	public String getCellMobileNumber() {
		return this.cellMobileNumber;
	}

	public void setCellMobileNumber(String cellMobileNumber) {
		this.cellMobileNumber = cellMobileNumber;
	}

	@Column(name = "email_address", length = 45)
	public String getEmailAddress() {
		return this.emailAddress;
	}

	public void setEmailAddress(String emailAddress) {
		this.emailAddress = emailAddress;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_first_rental", length = 19)
	public Date getDateFirstRental() {
		return this.dateFirstRental;
	}

	public void setDateFirstRental(Date dateFirstRental) {
		this.dateFirstRental = dateFirstRental;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_left_university", length = 19)
	public Date getDateLeftUniversity() {
		return this.dateLeftUniversity;
	}

	public void setDateLeftUniversity(Date dateLeftUniversity) {
		this.dateLeftUniversity = dateLeftUniversity;
	}

	@Column(name = "other_student_details", length = 45)
	public String getOtherStudentDetails() {
		return this.otherStudentDetails;
	}

	public void setOtherStudentDetails(String otherStudentDetails) {
		this.otherStudentDetails = otherStudentDetails;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "students")
	public Set<StudentRelationships> getStudentRelationshipses() {
		return this.studentRelationshipses;
	}

	public void setStudentRelationshipses(Set<StudentRelationships> studentRelationshipses) {
		this.studentRelationshipses = studentRelationshipses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "students")
	public Set<StudentClassRegistrations> getStudentClassRegistrationses() {
		return this.studentClassRegistrationses;
	}

	public void setStudentClassRegistrationses(Set<StudentClassRegistrations> studentClassRegistrationses) {
		this.studentClassRegistrationses = studentClassRegistrationses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "students")
	public Set<StudentsPaymentMethods> getStudentsPaymentMethodses() {
		return this.studentsPaymentMethodses;
	}

	public void setStudentsPaymentMethodses(Set<StudentsPaymentMethods> studentsPaymentMethodses) {
		this.studentsPaymentMethodses = studentsPaymentMethodses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "students")
	public Set<StudentAddress> getStudentAddresses() {
		return this.studentAddresses;
	}

	public void setStudentAddresses(Set<StudentAddress> studentAddresses) {
		this.studentAddresses = studentAddresses;
	}

}
