package org.demo.entity;
// Generated Oct 2, 2018 12:02:13 PM by Hibernate Tools 5.2.10.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * StudentClassRegistrations generated by hbm2java
 */
@Entity
@Table(name = "student_class_registrations", catalog = "studentregistration")
public class StudentClassRegistrations implements java.io.Serializable {

	private Date dateOfRegistration;
	private Classes classes;
	private Students students;
	private Date dateOfFirstClass;
	private Date dateOfLastClass;
	private String otherDetails;

	public StudentClassRegistrations() {
	}

	public StudentClassRegistrations(Date dateOfRegistration) {
		this.dateOfRegistration = dateOfRegistration;
	}

	public StudentClassRegistrations(Date dateOfRegistration, Classes classes, Students students, Date dateOfFirstClass,
			Date dateOfLastClass, String otherDetails) {
		this.dateOfRegistration = dateOfRegistration;
		this.classes = classes;
		this.students = students;
		this.dateOfFirstClass = dateOfFirstClass;
		this.dateOfLastClass = dateOfLastClass;
		this.otherDetails = otherDetails;
	}

	@Id

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_of_registration", unique = true, nullable = false, length = 19)
	public Date getDateOfRegistration() {
		return this.dateOfRegistration;
	}

	public void setDateOfRegistration(Date dateOfRegistration) {
		this.dateOfRegistration = dateOfRegistration;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "class_id")
	public Classes getClasses() {
		return this.classes;
	}

	public void setClasses(Classes classes) {
		this.classes = classes;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "student_id")
	public Students getStudents() {
		return this.students;
	}

	public void setStudents(Students students) {
		this.students = students;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_of_first_class", length = 19)
	public Date getDateOfFirstClass() {
		return this.dateOfFirstClass;
	}

	public void setDateOfFirstClass(Date dateOfFirstClass) {
		this.dateOfFirstClass = dateOfFirstClass;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_of_last_class", length = 19)
	public Date getDateOfLastClass() {
		return this.dateOfLastClass;
	}

	public void setDateOfLastClass(Date dateOfLastClass) {
		this.dateOfLastClass = dateOfLastClass;
	}

	@Column(name = "other_details", length = 45)
	public String getOtherDetails() {
		return this.otherDetails;
	}

	public void setOtherDetails(String otherDetails) {
		this.otherDetails = otherDetails;
	}

}
