package org.demo.entity;
// Generated Oct 2, 2018 12:02:13 PM by Hibernate Tools 5.2.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * StudentsPaymentMethods generated by hbm2java
 */
@Entity
@Table(name = "students_payment_methods", catalog = "studentregistration")
public class StudentsPaymentMethods implements java.io.Serializable {

	private Integer studentPaymentMethodId;
	private RefPaymentMethods refPaymentMethods;
	private Students students;
	private String bankDetails;
	private String cardDetails;
	private String otherDetails;

	public StudentsPaymentMethods() {
	}

	public StudentsPaymentMethods(RefPaymentMethods refPaymentMethods, Students students, String bankDetails,
			String cardDetails, String otherDetails) {
		this.refPaymentMethods = refPaymentMethods;
		this.students = students;
		this.bankDetails = bankDetails;
		this.cardDetails = cardDetails;
		this.otherDetails = otherDetails;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "student_payment_method_id", unique = true, nullable = false)
	public Integer getStudentPaymentMethodId() {
		return this.studentPaymentMethodId;
	}

	public void setStudentPaymentMethodId(Integer studentPaymentMethodId) {
		this.studentPaymentMethodId = studentPaymentMethodId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "payment_method_code")
	public RefPaymentMethods getRefPaymentMethods() {
		return this.refPaymentMethods;
	}

	public void setRefPaymentMethods(RefPaymentMethods refPaymentMethods) {
		this.refPaymentMethods = refPaymentMethods;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "student_id")
	public Students getStudents() {
		return this.students;
	}

	public void setStudents(Students students) {
		this.students = students;
	}

	@Column(name = "bank_details", length = 45)
	public String getBankDetails() {
		return this.bankDetails;
	}

	public void setBankDetails(String bankDetails) {
		this.bankDetails = bankDetails;
	}

	@Column(name = "card_details", length = 45)
	public String getCardDetails() {
		return this.cardDetails;
	}

	public void setCardDetails(String cardDetails) {
		this.cardDetails = cardDetails;
	}

	@Column(name = "other_details", length = 45)
	public String getOtherDetails() {
		return this.otherDetails;
	}

	public void setOtherDetails(String otherDetails) {
		this.otherDetails = otherDetails;
	}

}
