package org.demo.entity;
// Generated Oct 2, 2018 12:02:13 PM by Hibernate Tools 5.2.10.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * StudentRelationshipsId generated by hbm2java
 */
@Embeddable
public class StudentRelationshipsId implements java.io.Serializable {

	private int studentId;
	private int personId;

	public StudentRelationshipsId() {
	}

	public StudentRelationshipsId(int studentId, int personId) {
		this.studentId = studentId;
		this.personId = personId;
	}

	@Column(name = "student_id", nullable = false)
	public int getStudentId() {
		return this.studentId;
	}

	public void setStudentId(int studentId) {
		this.studentId = studentId;
	}

	@Column(name = "person_id", nullable = false)
	public int getPersonId() {
		return this.personId;
	}

	public void setPersonId(int personId) {
		this.personId = personId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof StudentRelationshipsId))
			return false;
		StudentRelationshipsId castOther = (StudentRelationshipsId) other;

		return (this.getStudentId() == castOther.getStudentId()) && (this.getPersonId() == castOther.getPersonId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getStudentId();
		result = 37 * result + this.getPersonId();
		return result;
	}

}
