package org.demo.entity;
// Generated Oct 2, 2018 12:02:13 PM by Hibernate Tools 5.2.10.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * StudentAddress generated by hbm2java
 */
@Entity
@Table(name = "student_address", catalog = "studentregistration")
public class StudentAddress implements java.io.Serializable {

	private Integer studentAddressId;
	private Addresses addresses;
	private RefAddressTypes refAddressTypes;
	private Students students;
	private Date dateAddressFrom;
	private Date dateAddressTo;
	private String monthlyRental;
	private String otherDetails;

	public StudentAddress() {
	}

	public StudentAddress(Addresses addresses, RefAddressTypes refAddressTypes, Students students, Date dateAddressFrom,
			Date dateAddressTo, String monthlyRental, String otherDetails) {
		this.addresses = addresses;
		this.refAddressTypes = refAddressTypes;
		this.students = students;
		this.dateAddressFrom = dateAddressFrom;
		this.dateAddressTo = dateAddressTo;
		this.monthlyRental = monthlyRental;
		this.otherDetails = otherDetails;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "student_address_id", unique = true, nullable = false)
	public Integer getStudentAddressId() {
		return this.studentAddressId;
	}

	public void setStudentAddressId(Integer studentAddressId) {
		this.studentAddressId = studentAddressId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "address_id")
	public Addresses getAddresses() {
		return this.addresses;
	}

	public void setAddresses(Addresses addresses) {
		this.addresses = addresses;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "address_type_code")
	public RefAddressTypes getRefAddressTypes() {
		return this.refAddressTypes;
	}

	public void setRefAddressTypes(RefAddressTypes refAddressTypes) {
		this.refAddressTypes = refAddressTypes;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "student_id")
	public Students getStudents() {
		return this.students;
	}

	public void setStudents(Students students) {
		this.students = students;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_address_from", length = 19)
	public Date getDateAddressFrom() {
		return this.dateAddressFrom;
	}

	public void setDateAddressFrom(Date dateAddressFrom) {
		this.dateAddressFrom = dateAddressFrom;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_address_to", length = 19)
	public Date getDateAddressTo() {
		return this.dateAddressTo;
	}

	public void setDateAddressTo(Date dateAddressTo) {
		this.dateAddressTo = dateAddressTo;
	}

	@Column(name = "monthly_rental", length = 45)
	public String getMonthlyRental() {
		return this.monthlyRental;
	}

	public void setMonthlyRental(String monthlyRental) {
		this.monthlyRental = monthlyRental;
	}

	@Column(name = "other_details", length = 45)
	public String getOtherDetails() {
		return this.otherDetails;
	}

	public void setOtherDetails(String otherDetails) {
		this.otherDetails = otherDetails;
	}

}
